/**
 * Single source of truth for the club ↔ organizer collaboration contract TEXT.
 *
 * Both the signed PDF (generateContractPDF.ts) AND the pre-signature review dialog
 * (CollabContractTermsDialog.tsx) render from this structure — so a signer reads the
 * exact terms that the PDF will contain, and the two can never drift.
 *
 * VERSIONING: the legal article text is a template. To keep a signed contract immutable,
 * the version in force at signature is frozen into event_collab_contracts.terms_snapshot
 * (terms_version), and the PDF re-renders THAT version at download — not the latest.
 * When you change the wording, bump COLLAB_TERMS_VERSION and ADD a new entry to REGISTRY,
 * never edit a published one (old contracts must keep rendering what was signed).
 */

export type Lang = 'fr' | 'en' | 'es';
export type L = { fr: string; en: string; es: string };
export const pickL = (lang: Lang | string, l: L): string =>
  (lang === 'en' ? l.en : lang === 'es' ? l.es : l.fr);

/** Bump + add a REGISTRY entry whenever the article wording changes. */
export const COLLAB_TERMS_VERSION = '2026-06-24';

export interface TermsClause {
  term: L;
  body: L;
  /** Alternate body used when the contract's cancellation policy === altWhen. */
  bodyAlt?: L;
  altWhen?: 'no_refund_after_event' | 'pro_rata_refund';
}

export type TermsArticle =
  | { num: number; kind: 'parties'; title: L }
  | { num: number; kind: 'split'; title: L; note: L }
  | { num: number; kind: 'static'; title: L; intro?: L; clauses?: TermsClause[] };

export interface CollabTermsLabels {
  docTitle: L;
  collaboration: L;
  clubRole: L;
  orgRole: L;
  event: L;
  date: L;
  denom: L;
  address: L;
  reg: L;
  vat: L;
  ticketsRow: L;
  tablesRow: L;
  drinksRow: L;
  orgShort: L;
  signaturesTitle: L;
  forClub: L;
  forOrg: L;
  signedOn: L;
  notSigned: L;
  footer: L;
}

export interface CollabTerms {
  version: string;
  articles: TermsArticle[];
  labels: CollabTermsLabels;
}

// ── v2026-06-24 — first fully-articled contract ──────────────────────────────
const LABELS_2026_06_24: CollabTermsLabels = {
  docTitle: { fr: 'Contrat de collaboration de soirée', en: 'Event collaboration contract', es: 'Contrato de colaboración de evento' },
  collaboration: { fr: 'Collaboration', en: 'Collaboration', es: 'Colaboración' },
  clubRole: { fr: 'Club (lieu, vendeur de record)', en: 'Club (venue, seller of record)', es: 'Club (local, vendedor de registro)' },
  orgRole: { fr: 'Organisateur', en: 'Organizer', es: 'Organizador' },
  event: { fr: 'Soirée', en: 'Event', es: 'Evento' },
  date: { fr: 'Date', en: 'Date', es: 'Fecha' },
  denom: { fr: 'Dénomination sociale', en: 'Registered name', es: 'Razón social' },
  address: { fr: 'Adresse', en: 'Address', es: 'Dirección' },
  reg: { fr: "N° d'immatriculation (SIRET / NIF)", en: 'Registration no. (SIRET / NIF)', es: 'N.º de registro (SIRET / NIF)' },
  vat: { fr: 'N° TVA', en: 'VAT no.', es: 'N.º IVA' },
  ticketsRow: { fr: 'Billets', en: 'Tickets', es: 'Entradas' },
  tablesRow: { fr: 'Tables / VIP', en: 'Tables / VIP', es: 'Mesas / VIP' },
  drinksRow: { fr: 'Boissons', en: 'Drinks', es: 'Bebidas' },
  orgShort: { fr: 'Orga', en: 'Org', es: 'Org' },
  signaturesTitle: { fr: 'Signatures électroniques', en: 'Electronic signatures', es: 'Firmas electrónicas' },
  forClub: { fr: 'Pour le Club', en: 'For the Club', es: 'Por el Club' },
  forOrg: { fr: "Pour l'Organisateur", en: 'For the Organizer', es: 'Por el Organizador' },
  signedOn: { fr: 'Signé le', en: 'Signed on', es: 'Firmado el' },
  notSigned: { fr: 'Non signé', en: 'Not signed', es: 'Sin firmar' },
  footer: {
    fr: "Document généré par Yuno. Signature électronique simple (eIDAS) — la preuve juridique est l'horodatage et l'adresse IP enregistrés.",
    en: 'Document generated by Yuno. Simple electronic signature (eIDAS) — the legal evidence is the recorded timestamp and IP address.',
    es: 'Documento generado por Yuno. Firma electrónica simple (eIDAS) — la prueba legal es la marca de tiempo y la IP registradas.',
  },
};

const ARTICLES_2026_06_24: TermsArticle[] = [
  { num: 1, kind: 'parties', title: { fr: 'Parties', en: 'Parties', es: 'Partes' } },
  {
    num: 2,
    kind: 'static',
    title: { fr: 'Objet & définitions', en: 'Purpose & definitions', es: 'Objeto y definiciones' },
    intro: {
      fr: "Le présent contrat régit la répartition des revenus de billetterie, des tables / VIP et des boissons vendus via Yuno pour la soirée désignée ci-dessus, ainsi que les modalités d'encaissement et de reversement entre les parties.",
      en: 'This contract governs the split of ticketing, tables / VIP and drinks revenue sold through Yuno for the event identified above, together with how funds are collected and paid out between the parties.',
      es: 'Este contrato regula el reparto de los ingresos de entradas, mesas / VIP y bebidas vendidos a través de Yuno para el evento indicado arriba, así como el cobro y el abono entre las partes.',
    },
    clauses: [
      {
        term: { fr: 'Billet', en: 'Ticket', es: 'Entrada' },
        body: {
          fr: "Droit d'entrée à la soirée vendu via Yuno. N'inclut aucune consommation, sauf mention expresse dans l'offre.",
          en: 'Right of entry to the event sold through Yuno. Includes no drinks unless the offer expressly states otherwise.',
          es: 'Derecho de entrada al evento vendido a través de Yuno. No incluye ninguna consumición salvo que la oferta lo indique expresamente.',
        },
      },
      {
        term: { fr: 'Table / VIP', en: 'Table / VIP', es: 'Mesa / VIP' },
        body: {
          fr: "Réservation d'un emplacement (table, carré, espace VIP). Les bouteilles et consommations rattachées à une table relèvent de la catégorie « Boissons » et reviennent au Club.",
          en: 'Reservation of a spot (table, booth, VIP area). Bottles and drinks attached to a table fall under the "Drinks" category and belong to the Club.',
          es: 'Reserva de un espacio (mesa, reservado, zona VIP). Las botellas y consumiciones asociadas a una mesa pertenecen a la categoría «Bebidas» y corresponden al Club.',
        },
      },
      {
        term: { fr: 'Boisson', en: 'Drink', es: 'Bebida' },
        body: {
          fr: "Toute consommation (bouteille, conso, soft, alcool) vendue via Yuno. Le Club détient la licence et demeure le vendeur des boissons.",
          en: 'Any consumable (bottle, drink, soft, alcohol) sold through Yuno. The Club holds the licence and remains the seller of the drinks.',
          es: 'Cualquier consumición (botella, copa, refresco, alcohol) vendida a través de Yuno. El Club posee la licencia y sigue siendo el vendedor de las bebidas.',
        },
      },
      {
        term: { fr: 'Offre groupée', en: 'Bundle', es: 'Paquete' },
        body: {
          fr: "Pour une offre combinant plusieurs catégories (ex. « entrée + bouteille » ou prévente avec consommation incluse), chaque composante est ventilée : la valeur du droit d'entrée suit la répartition Billets, et la valeur de la consommation suit la répartition Boissons.",
          en: 'For an offer combining several categories (e.g. "entry + bottle" or a presale with a drink included), each component is allocated separately: the entry value follows the Tickets split and the drink value follows the Drinks split.',
          es: 'Para una oferta que combine varias categorías (p. ej. «entrada + botella» o preventa con consumición incluida), cada componente se imputa por separado: el valor de la entrada sigue el reparto de Entradas y el valor de la consumición sigue el reparto de Bebidas.',
        },
      },
    ],
  },
  {
    num: 3,
    kind: 'split',
    title: { fr: 'Répartition des revenus', en: 'Revenue split', es: 'Reparto de ingresos' },
    note: {
      fr: "Les paiements sont encaissés au nom du Club (vendeur de record, alcool inclus). Yuno reverse automatiquement à chaque vente la part de l'organisateur selon les pourcentages ci-dessus. Les boissons reviennent toujours à 100% au Club, sauf si l'organisateur a attesté ses propres documents de vente d'alcool.",
      en: "Payments are collected under the Club (seller of record, alcohol included). Yuno automatically pays out the organizer's share on each sale per the percentages above. Drinks are always 100% the Club's, unless the organizer has attested their own alcohol-sale documents.",
      es: "Los pagos se cobran a nombre del Club (vendedor de registro, alcohol incluido). Yuno abona automáticamente la parte del organizador en cada venta según los porcentajes anteriores. Las bebidas son siempre 100% del Club, salvo que el organizador haya acreditado sus propios documentos de venta de alcohol.",
    },
  },
  {
    num: 4,
    kind: 'static',
    title: { fr: 'Assiette, frais & commissions', en: 'Base, fees & commission', es: 'Base, gastos y comisión' },
    clauses: [
      {
        term: { fr: 'Commission Yuno', en: 'Yuno commission', es: 'Comisión Yuno' },
        body: {
          fr: "4 % sur les billets et les tables (minimum 0,99 € par vente ; 0,49 € pour les organisateurs BDE vérifiés) et 3 % sur les boissons. Cette commission est ajoutée au prix et réglée par le client lors de l'achat ; Yuno la conserve intégralement.",
          en: '4% on tickets and tables (minimum €0.99 per sale; €0.49 for verified student-union (BDE) organizers) and 3% on drinks. This commission is added on top of the price and paid by the customer at checkout; Yuno keeps it in full.',
          es: '4 % en entradas y mesas (mínimo 0,99 € por venta; 0,49 € para organizadores BDE verificados) y 3 % en bebidas. Esta comisión se añade al precio y la paga el cliente en la compra; Yuno la conserva íntegramente.',
        },
      },
      {
        term: { fr: 'Assiette de la répartition', en: 'Split base', es: 'Base del reparto' },
        body: {
          fr: "Les pourcentages convenus s'appliquent au prix de l'article (TTC) effectivement encaissé, après déduction de la commission Yuno.",
          en: 'The agreed percentages apply to the item price (incl. tax) actually collected, after deducting the Yuno commission.',
          es: 'Los porcentajes acordados se aplican al precio del artículo (IVA incluido) efectivamente cobrado, tras deducir la comisión de Yuno.',
        },
      },
      {
        term: { fr: 'Frais de paiement (Stripe)', en: 'Payment fees (Stripe)', es: 'Comisiones de pago (Stripe)' },
        body: {
          fr: "Les frais de traitement carte (environ 1,5 % + 0,25 € par transaction) sont supportés par les parties au prorata de leur part respective dans chaque vente. Yuno ne supporte pas ces frais.",
          en: 'Card processing fees (about 1.5% + €0.25 per transaction) are borne by the parties pro rata to their respective share of each sale. Yuno does not bear these fees.',
          es: 'Las comisiones de procesamiento de tarjeta (alrededor del 1,5 % + 0,25 € por transacción) corren a cargo de las partes en proporción a su parte respectiva en cada venta. Yuno no asume estas comisiones.',
        },
      },
      {
        term: { fr: 'TVA & facturation', en: 'VAT & invoicing', es: 'IVA y facturación' },
        body: {
          fr: "Le Club étant vendeur de record, il encaisse en son nom, collecte la TVA applicable et émet le reçu fiscal au client. Chaque partie demeure responsable de ses propres obligations fiscales et déclaratives sur sa part de revenu.",
          en: "As the seller of record, the Club collects in its own name, charges the applicable VAT and issues the customer's tax receipt. Each party remains responsible for its own tax and reporting obligations on its share of revenue.",
          es: 'Al ser el vendedor de registro, el Club cobra en su nombre, repercute el IVA aplicable y emite el recibo fiscal al cliente. Cada parte sigue siendo responsable de sus propias obligaciones fiscales y declarativas sobre su parte de los ingresos.',
        },
      },
    ],
  },
  {
    num: 5,
    kind: 'static',
    title: { fr: 'Remboursements & rétrofacturation', en: 'Refunds & chargebacks', es: 'Reembolsos y contracargos' },
    clauses: [
      {
        term: { fr: 'Remboursement', en: 'Refund', es: 'Reembolso' },
        body: {
          fr: "Chaque remboursement reprend proportionnellement la part de chaque partie : la somme remboursée est débitée de chaque partie au prorata de ce qu'elle a perçu sur la vente concernée.",
          en: "Each refund proportionally reverses each party's share: the refunded amount is debited from each party pro rata to what it received on the relevant sale.",
          es: 'Cada reembolso revierte proporcionalmente la parte de cada parte: el importe reembolsado se carga a cada parte en proporción a lo que percibió en la venta correspondiente.',
        },
        altWhen: 'no_refund_after_event',
        bodyAlt: {
          fr: "Aucun remboursement n'est dû après la tenue de la soirée. Avant la soirée, chaque remboursement reprend proportionnellement la part de chaque partie sur la vente concernée.",
          en: "No refund is due once the event has taken place. Before the event, each refund proportionally reverses each party's share of the relevant sale.",
          es: 'No procede reembolso una vez celebrado el evento. Antes del evento, cada reembolso revierte proporcionalmente la parte de cada parte en la venta correspondiente.',
        },
      },
      {
        term: { fr: 'Rétrofacturation (chargeback)', en: 'Chargeback', es: 'Contracargo (chargeback)' },
        body: {
          fr: "En cas de contestation d'un paiement par le client (chargeback) ou d'impayé, la perte et les frais associés sont repris au prorata de la part de chaque partie sur la vente concernée, par reprise du virement déjà effectué. Aucune partie ne supporte la part de l'autre.",
          en: "If a customer disputes a payment (chargeback) or a payment fails, the loss and related fees are reversed pro rata to each party's share of the relevant sale, by clawing back the transfer already made. Neither party bears the other's share.",
          es: 'Si un cliente disputa un pago (contracargo) o se produce un impago, la pérdida y los gastos asociados se reparten en proporción a la parte de cada parte en la venta correspondiente, revirtiendo la transferencia ya realizada. Ninguna parte asume la parte de la otra.',
        },
      },
    ],
  },
  {
    num: 6,
    kind: 'static',
    title: { fr: 'Annulation & force majeure', en: 'Cancellation & force majeure', es: 'Cancelación y fuerza mayor' },
    clauses: [
      {
        term: { fr: 'Annulation par une partie', en: 'Cancellation by a party', es: 'Cancelación por una parte' },
        body: {
          fr: "Si le Club ou l'Organisateur annule la soirée, la partie qui annule en informe l'autre et Yuno sans délai. Les billets, tables et boissons déjà vendus sont remboursés aux clients, chaque partie reprenant sa part au prorata.",
          en: 'If the Club or the Organizer cancels the event, the cancelling party informs the other and Yuno without delay. Tickets, tables and drinks already sold are refunded to customers, each party reversing its share pro rata.',
          es: 'Si el Club o el Organizador cancela el evento, la parte que cancela informa a la otra y a Yuno sin demora. Las entradas, mesas y bebidas ya vendidas se reembolsan a los clientes, revirtiendo cada parte su parte en proporción.',
        },
      },
      {
        term: { fr: 'Fermeture administrative', en: 'Administrative closure', es: 'Cierre administrativo' },
        body: {
          fr: "En cas de fermeture ordonnée par une autorité (mairie, préfecture, police, pompiers) ou de retrait d'autorisation, l'événement est réputé annulé pour cause de force majeure : les ventes sont remboursées aux clients au prorata des parts et aucune partie ne doit de dommages à l'autre à ce titre.",
          en: 'If an authority (city hall, prefecture, police, fire service) orders a closure or withdraws an authorization, the event is deemed cancelled for force majeure: sales are refunded to customers pro rata to the shares and neither party owes the other any damages on that basis.',
          es: 'Si una autoridad (ayuntamiento, subdelegación, policía, bomberos) ordena el cierre o retira una autorización, el evento se considera cancelado por fuerza mayor: las ventas se reembolsan a los clientes en proporción a las partes y ninguna parte debe a la otra indemnización alguna por ello.',
        },
      },
      {
        term: { fr: 'Force majeure', en: 'Force majeure', es: 'Fuerza mayor' },
        body: {
          fr: "Aucune partie n'est responsable de l'inexécution résultant d'un événement de force majeure (catastrophe, intempérie majeure, grève, coupure d'énergie, décision administrative, épidémie, etc.). Les sommes encaissées et non utilisées sont remboursées aux clients au prorata des parts.",
          en: 'Neither party is liable for non-performance caused by a force majeure event (disaster, severe weather, strike, power outage, administrative decision, epidemic, etc.). Amounts collected and not used are refunded to customers pro rata to the shares.',
          es: 'Ninguna parte es responsable del incumplimiento derivado de un caso de fuerza mayor (catástrofe, temporal grave, huelga, corte de energía, decisión administrativa, epidemia, etc.). Los importes cobrados y no utilizados se reembolsan a los clientes en proporción a las partes.',
        },
      },
    ],
  },
  {
    num: 7,
    kind: 'static',
    title: { fr: 'Preuve', en: 'Evidence', es: 'Prueba' },
    intro: {
      fr: "Les données enregistrées par Yuno — commandes, ventes, remboursements, montants, répartitions, horodatages et adresses IP — font foi entre les parties, sauf preuve contraire. Les relevés Yuno servent de base au calcul des parts et des reversements.",
      en: "The data recorded by Yuno — orders, sales, refunds, amounts, splits, timestamps and IP addresses — is authoritative between the parties unless proven otherwise. Yuno's records are the basis for calculating shares and payouts.",
      es: 'Los datos registrados por Yuno — pedidos, ventas, reembolsos, importes, repartos, marcas de tiempo y direcciones IP — dan fe entre las partes salvo prueba en contrario. Los registros de Yuno sirven de base para calcular las partes y los abonos.',
    },
  },
  {
    num: 8,
    kind: 'static',
    title: { fr: 'Rôle & responsabilité de Yuno', en: "Yuno's role & liability", es: 'Función y responsabilidad de Yuno' },
    intro: {
      fr: "Yuno agit uniquement comme plateforme technique de billetterie, d'encaissement et de répartition des revenus entre le Club et l'Organisateur. Yuno n'organise pas la soirée, n'y est pas partie et ne peut être tenue responsable de son annulation, de son déroulement, de la sécurité, ni des obligations respectives du Club et de l'Organisateur (licences, autorisations, fiscalité, droit du travail). Le Club et l'Organisateur garantissent Yuno contre toute réclamation de tiers liée à l'événement.",
      en: "Yuno acts solely as the technical platform for ticketing, collection and revenue split between the Club and the Organizer. Yuno does not organize the event, is not a party to it and cannot be held liable for its cancellation, its conduct, safety, or the respective obligations of the Club and the Organizer (licences, authorizations, taxes, labour law). The Club and the Organizer indemnify Yuno against any third-party claim related to the event.",
      es: 'Yuno actúa únicamente como plataforma técnica de venta de entradas, cobro y reparto de ingresos entre el Club y el Organizador. Yuno no organiza el evento, no es parte del mismo y no puede ser considerada responsable de su cancelación, su desarrollo, la seguridad ni de las obligaciones respectivas del Club y el Organizador (licencias, autorizaciones, fiscalidad, derecho laboral). El Club y el Organizador mantienen indemne a Yuno frente a cualquier reclamación de terceros relacionada con el evento.',
    },
  },
];

const TERMS_2026_06_24: CollabTerms = {
  version: COLLAB_TERMS_VERSION,
  articles: ARTICLES_2026_06_24,
  labels: LABELS_2026_06_24,
};

/** Every published version is kept here forever so signed contracts re-render as signed. */
const REGISTRY: Record<string, CollabTerms> = {
  [COLLAB_TERMS_VERSION]: TERMS_2026_06_24,
};

/** Resolve the terms for a frozen version; unknown / legacy-null falls back to latest. */
export function getCollabTerms(version?: string | null): CollabTerms {
  return (version && REGISTRY[version]) || TERMS_2026_06_24;
}

/** Pick the clause body, honoring the policy-dependent alternate when it applies. */
export function clauseBody(c: TermsClause, cancellationPolicy?: string): L {
  if (c.altWhen && c.bodyAlt && cancellationPolicy === c.altWhen) return c.bodyAlt;
  return c.body;
}
