#!/usr/bin/env bash
# Build a real design-system package for design-sync — PUBLIC system only.
#
# Scope decision (2026-07-19): Claude Design carries docs/DESIGN_SYSTEM_PUBLIC.md
# only, so this exports the public/editorial surface, not the pro dashboards.
# The module list below is usage-derived: every ui/ primitive imported by a public
# page or by src/components/explore/*, plus the public nav and the editorial
# components themselves. The 18 pro-only primitives (sidebar, dropdown-menu,
# accordion, popover, toast...) are deliberately absent — see NOTES.md.
#
# Why a package at all: Yuno is an app, not a published library. design-sync reads
# props from the .d.ts tree, NOT from sources, so without generated declarations
# every component would ship `[key: string]: unknown` and the design agent would
# learn nothing about variant/size/asChild.
#
# Outputs (all gitignored, regenerated by cfg.buildCmd):
#   src/components/__ds-entry.ts           barrel over the scoped modules
#   .design-sync/ds-package/types/**       tsc declarations (the prop contracts)
#   .design-sync/ds-package/index.mjs      esbuild bundle (react kept external)
#   .design-sync/ds-package/package.json   carries `types` so extraction works
#   .design-sync/ds-package/yuno-styles.css  cssEntry must live inside the package
#
# The barrel is a .ts file, which design-sync's source walk ignores (it globs
# .tsx/.jsx/.md only), so it never surfaces as a component.
set -euo pipefail
cd "$(dirname "$0")/.."

PKG=.design-sync/ds-package
ENTRY=src/components/__ds-entry.ts
PROVIDER=src/components/__ds-preview-provider.tsx
mkdir -p "$PKG"

# ── 0. Preview provider. The editorial components read router, language and
#    favorites context (EventCard: useNavigate + useLanguage + useFavorites), so
#    without this wrapper their cards render empty. Generated inside src/ so tsc's
#    rootDir still covers it; gitignored, and excluded from the component list via
#    cfg.componentSrcMap so it ships in the bundle without becoming a card.
cat > "$PROVIDER" <<'TSX'
// Generated by .design-sync/build-ds-package.sh — do not edit.
import { ReactNode } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { LanguageProvider } from '@/contexts/LanguageContext';
import { FavoritesProvider } from '@/contexts/FavoritesContext';

export function YunoPreviewProvider({ children }: { children: ReactNode }) {
  return (
    <MemoryRouter>
      <LanguageProvider>
        <FavoritesProvider>{children}</FavoritesProvider>
      </LanguageProvider>
    </MemoryRouter>
  );
}
TSX

# ── 1. Barrel over the public scope.
node - "$ENTRY" <<'EOF'
const fs = require('fs');
const out = process.argv[2];

// ui/ primitives reachable from public surfaces (usage-derived, see header).
const ui = [
  'avatar', 'badge', 'bottom-nav-bar', 'button', 'calendar', 'card', 'checkbox',
  'dialog', 'drawer', 'input', 'input-otp', 'label', 'select', 'separator',
  'skeleton', 'slider', 'tabs', 'textarea', 'AnimatedOrb',
];
// Editorial components — the public system's own vocabulary.
const explore = [
  'EventCard', 'ExploreChipRow', 'ExploreDJCard', 'ExploreDayTabs',
  'ExploreEventCarousel', 'ExploreListRow', 'ExplorePopularClubCard',
  'ExploreRailCard', 'ExploreRankCard', 'ExploreSectionTitle',
  'ExploreSeeAllCard', 'ExploreVenueCard',
];
const extra = ['BottomNav', '__ds-preview-provider']; // nav shell + preview context wrapper

const missing = [];
const line = (dir, m) => {
  const p = dir ? `src/components/${dir}/${m}.tsx` : `src/components/${m}.tsx`;
  if (!fs.existsSync(p)) { missing.push(p); return null; }
  return `export * from ${JSON.stringify(dir ? `./${dir}/${m}` : `./${m}`)};`;
};

const lines = ['// Generated by .design-sync/build-ds-package.sh — do not edit.'];
for (const m of ui) lines.push(line('ui', m));
for (const m of explore) lines.push(line('explore', m));
for (const m of extra) lines.push(line('', m));

if (missing.length) {
  console.error('build-ds-package: missing modules:\n  ' + missing.join('\n  '));
  process.exit(1);
}
fs.writeFileSync(out, lines.filter(Boolean).join('\n') + '\n');
console.error(`  barrel: ${ui.length + explore.length + extra.length} modules -> ${out}`);
EOF

# ── 2. Declarations. Declaration emit on Radix/forwardRef code reliably produces
#    "cannot be named" errors; tsc still writes the .d.ts files, so judge by
#    output, not exit code.
#    `paths` is rejected on the command line (TS6064), so emit a real tsconfig.
rm -rf "$PKG/types"
cat > "$PKG/tsconfig.dts.json" <<'JSON'
{
  "compilerOptions": {
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "types",
    "rootDir": "../../src",
    "baseUrl": "../..",
    "paths": { "@/*": ["src/*"] },
    "jsx": "react-jsx",
    "module": "esnext",
    "moduleResolution": "bundler",
    "target": "ES2020",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "strict": false,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "files": ["../../src/components/__ds-entry.ts"]
}
JSON
npx tsc -p "$PKG/tsconfig.dts.json" > "$PKG/.tsc.log" 2>&1 || true

DTS=$PKG/types/components/__ds-entry.d.ts
if [ ! -f "$DTS" ]; then
  echo "build-ds-package: tsc emitted no declarations at $DTS" >&2
  tail -20 "$PKG/.tsc.log" >&2
  exit 1
fi
echo "  types:  $(find "$PKG/types" -name '*.d.ts' | wc -l | tr -d ' ') .d.ts files"

# ── 3. JS bundle. react/react-dom stay external — design-sync vendors its own.
#    (esbuild's bin/ is a native binary, so go through the JS API, resolved from
#    the staged converter deps.)
node --input-type=module - "$ENTRY" "$PKG/index.mjs" <<'EOF'
import { createRequire } from 'node:module';
const require = createRequire(process.cwd() + '/.ds-sync/package.json');
const esbuild = require('esbuild');
const [entry, outfile] = process.argv.slice(2);
await esbuild.build({
  entryPoints: [entry], outfile, bundle: true, format: 'esm',
  platform: 'browser', target: 'es2020', jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  tsconfig: 'tsconfig.app.json', logLevel: 'warning',
  // The barrel transitively pulls in integrations/supabase/client.ts, which
  // reads import.meta.env at module scope and throws "supabaseUrl is required"
  // the moment anything imports it — that killed all 72 preview cards. Feed it
  // inert placeholders: previews must never reach the network, and this keeps
  // the project's real (even if public) credentials out of the design bundle.
  define: {
    'import.meta.env.VITE_SUPABASE_URL': '"https://placeholder.supabase.co"',
    'import.meta.env.VITE_SUPABASE_ANON_KEY': '"design-sync-placeholder-anon-key"',
    'import.meta.env': '{}',
  },
});
EOF

# ── 4. Manifest + stylesheet (cssEntry is bounded to the package dir).
cat > "$PKG/package.json" <<JSON
{
  "name": "yuno-design-system",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "module": "index.mjs",
  "types": "types/components/__ds-entry.d.ts"
}
JSON

cp .design-sync/yuno-styles.css "$PKG/yuno-styles.css"
echo "  bundle: $(wc -c < "$PKG/index.mjs" | tr -d ' ') bytes -> $PKG/index.mjs"
