#!/usr/bin/env bash
# Stage the app's compiled Tailwind CSS for design-sync.
#
# Why this exists: Yuno is an app, not a published component library. src/index.css
# is raw Tailwind (@tailwind base/components/utilities) — shipping it would leave
# every card unstyled because no utility class exists until Tailwind compiles it.
# `npm run build` emits the real thing at dist/assets/index-<hash>.css, but the
# hash changes every build, so cfg.cssEntry can't point at it directly.
#
# This copies it to a stable path and prepends the Google Fonts @import that
# index.html normally provides via <link> (Inter / Space Grotesk / JetBrains Mono
# / Cormorant Garamond / Poppins). Without that line the DS renders in fallback
# fonts and nothing downstream catches it.
#
# Output (.design-sync/yuno-styles.css) is gitignored — regenerated from buildCmd.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=$(ls -S dist/assets/index-*.css 2>/dev/null | head -1)
if [ -z "${SRC:-}" ]; then
  echo "prepare-css: no dist/assets/index-*.css — run 'npm run build' first" >&2
  exit 1
fi

OUT=.design-sync/yuno-styles.css
{
  echo "/* Yuno design system — compiled Tailwind + brand tokens. Generated by .design-sync/prepare-css.sh, do not edit. */"
  echo "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Space+Grotesk:wght@500;600;700&family=JetBrains+Mono:wght@400;500;700&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&family=Poppins:wght@500&display=swap');"
  cat "$SRC"

  # design-sync's preview harness hardcodes a light card chrome
  # (`body{background:#fff}`, #e5e7eb cell borders) in an inline <style> that
  # comes after our stylesheets. Yuno's public DS is dark-first, so on white
  # every card lies: `ghost` buttons go invisible and `outline` reads as a solid
  # black slab. Scoped to the harness's own grid via :has(), so real designs
  # built with the DS keep full control of their background — and the higher
  # specificity beats the inline block without needing !important.
  cat <<'CSS'

/* ── design-sync preview harness: force the dark canvas the DS assumes ── */
body:has(> .ds-grid), body:has(> .ds-single) {
  background: var(--yuno-black);
  color: var(--yuno-white);
  font-family: 'Inter', system-ui, sans-serif;
}
body:has(> .ds-grid) .ds-cell, body:has(> .ds-single) .ds-cell {
  border-color: var(--border-subtle);
  background: transparent;
}
body:has(> .ds-grid) .ds-cell > h4, body:has(> .ds-single) .ds-cell > h4 {
  color: var(--yuno-gray-3);
  font-family: 'JetBrains Mono', ui-monospace, monospace;
}
CSS
} > "$OUT"

echo "prepare-css: $SRC -> $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
