import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/contexts/LanguageContext';
import { useToast } from '@/hooks/use-toast';
import { useUnsavedGuard } from '@/hooks/useUnsavedGuard';
import { ArrowLeft, Save, Sparkles, Megaphone, Info } from 'lucide-react';
import {
  AffPage, AffCard, AffCardHeader, AffButton, Pill, AffSpinner,
  FieldLabel, DarkInput, DarkTextarea,
  T1, T3, INNER_BG, BORDER,
} from '@/components/affiliate/affiliate-ui';

type BriefForm = {
  instagram_caption: string;
  hashtags: string;
  door_time: string;
  dress_code: string;
  lineup_notes: string;
  promo_notes: string;
  extra_info: string;
  brief_flyer_url: string;
};

const EMPTY_FORM: BriefForm = {
  instagram_caption: '', hashtags: '', door_time: '', dress_code: '',
  lineup_notes: '', promo_notes: '', extra_info: '', brief_flyer_url: '',
};

export default function AffiliateEventBrief() {
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const { t } = useLanguage();
  const { toast } = useToast();
  const [eventName, setEventName] = useState('');
  const [form, setForm] = useState<BriefForm>(EMPTY_FORM);
  const [briefId, setBriefId] = useState<string | null>(null);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  // Promoteurs et managers (affiliate_members) lisent le brief sans l'éditer :
  // seul le chef d'agence (ligne affiliates) écrit. Avant, un membre tombait
  // sur un FORMULAIRE VIDE éditable — et Enregistrer insérait un 2e brief.
  const [readOnly, setReadOnly] = useState(false);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (user && id) fetchBrief();
  }, [user?.id, id]);

  const fetchBrief = async () => {
    setLoading(true);
    const { data: aff } = await supabase.from('affiliates').select('id').eq('user_id', user!.id).maybeSingle();
    let affiliateId = aff?.id ?? null;
    let viewerIsAdmin = !!aff;
    if (!affiliateId) {
      const { data: member } = await supabase
        .from('affiliate_members')
        .select('affiliate_id')
        .eq('user_id', user!.id)
        .eq('is_active', true)
        .maybeSingle();
      affiliateId = member?.affiliate_id ?? null;
      viewerIsAdmin = false;
    }
    if (!affiliateId) { setNotFound(true); setLoading(false); return; }
    setReadOnly(!viewerIsAdmin);

    const { data: ev } = await supabase
      .from('affiliate_events')
      .select('name')
      .eq('id', id!)
      .eq('affiliate_id', affiliateId)
      .maybeSingle();
    if (!ev) { setNotFound(true); setLoading(false); return; }
    setEventName(ev.name);

    const { data: brief } = await supabase
      .from('affiliate_event_briefs')
      .select('*')
      .eq('affiliate_event_id', id!)
      .maybeSingle();

    if (brief) {
      setBriefId(brief.id);
      setIsAutoGenerated(brief.is_auto_generated ?? false);
      setForm({
        instagram_caption: brief.instagram_caption ?? '',
        hashtags: brief.hashtags ?? '',
        door_time: brief.door_time ?? '',
        dress_code: brief.dress_code ?? '',
        lineup_notes: brief.lineup_notes ?? '',
        promo_notes: brief.promo_notes ?? '',
        extra_info: brief.extra_info ?? '',
        brief_flyer_url: brief.brief_flyer_url ?? '',
      });
    }
    setLoading(false);
  };

  const handleSave = async (): Promise<boolean> => {
    if (readOnly) return false;
    setSaving(true);
    const payload = {
      affiliate_event_id: id!,
      instagram_caption: form.instagram_caption || null,
      hashtags: form.hashtags || null,
      door_time: form.door_time || null,
      dress_code: form.dress_code || null,
      lineup_notes: form.lineup_notes || null,
      promo_notes: form.promo_notes || null,
      extra_info: form.extra_info || null,
      brief_flyer_url: form.brief_flyer_url || null,
      is_auto_generated: false,
    };

    let error;
    if (briefId) {
      ({ error } = await supabase.from('affiliate_event_briefs').update(payload).eq('id', briefId));
    } else {
      const { data, error: insertError } = await supabase
        .from('affiliate_event_briefs')
        .insert(payload)
        .select('id')
        .single();
      error = insertError;
      if (data) setBriefId(data.id);
    }

    setSaving(false);
    if (error) {
      toast({ title: t('aff.brief.toast.error'), description: error.message, variant: 'destructive' });
      return false;
    }
    setIsAutoGenerated(false);
    markSaved();
    toast({ title: t('aff.brief.toast.saved') });
    return true;
  };

  const { markSaved, guardedNavigate } = useUnsavedGuard({
    scope: `affiliate-brief:${id ?? 'new'}`,
    label: t('aff.brief.title'),
    ready: !loading && !readOnly,
    value: form,
    onRestore: setForm,
    onSave: handleSave,
  });

  const set = (key: keyof BriefForm) => (v: string) => setForm(f => ({ ...f, [key]: v }));

  if (loading) return <AffSpinner />;

  if (notFound) {
    return (
      <AffPage maxWidth={760}>
        <AffCard padding={28}>
          <p style={{ color: T1, fontSize: 15, fontWeight: 600, margin: 0 }}>{t('aff.brief.notFound')}</p>
          <p style={{ color: T3, fontSize: 13, marginTop: 6 }}>{t('aff.brief.notFoundDesc')}</p>
        </AffCard>
      </AffPage>
    );
  }

  return (
    <AffPage maxWidth={760}>
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex items-center gap-3">
        <button onClick={() => guardedNavigate('/affiliate/events')}
          className="flex items-center justify-center transition-colors flex-none"
          style={{ width: 36, height: 36, borderRadius: 10, background: INNER_BG, border: `1px solid ${BORDER}`, color: T3 }}
          onMouseEnter={(e) => (e.currentTarget.style.color = T1)} onMouseLeave={(e) => (e.currentTarget.style.color = T3)}>
          <ArrowLeft className="h-4 w-4" />
        </button>
        <div className="flex-1 min-w-0">
          <h1 style={{ color: T1, fontSize: 'clamp(20px,2.4vw,26px)', fontWeight: 680, letterSpacing: '-0.02em', margin: 0 }}>{t('aff.brief.title')}</h1>
          <p className="truncate" style={{ color: T3, fontSize: 13, marginTop: 2 }}>{eventName}</p>
        </div>
        {readOnly
          ? <Pill><span className="inline-flex items-center gap-1">{t('aff.brief.readOnly')}</span></Pill>
          : isAutoGenerated && <Pill tone="red"><span className="inline-flex items-center gap-1"><Sparkles className="h-3 w-3" /> {t('aff.brief.autoGenerated')}</span></Pill>}
      </motion.div>

      <AffCard padding={20}>
        <AffCardHeader icon={Megaphone} title={t('aff.brief.promoContent')} subtitle={t('aff.brief.promoContentSub')} accent />
        <div className="space-y-4">
          <div>
            <FieldLabel>{t('aff.brief.instagramCaption')}</FieldLabel>
            <DarkTextarea value={form.instagram_caption} onChange={set('instagram_caption')} placeholder={t('aff.brief.instagramCaptionPh')} rows={5} disabled={readOnly} />
          </div>
          <div>
            <FieldLabel>{t('aff.brief.hashtags')}</FieldLabel>
            <DarkInput value={form.hashtags} onChange={set('hashtags')} placeholder={t('aff.brief.hashtagsPh')} disabled={readOnly} />
          </div>
          <div>
            <FieldLabel hint={t('aff.brief.flyerHint')}>{t('aff.brief.flyerUrl')}</FieldLabel>
            <DarkInput value={form.brief_flyer_url} onChange={set('brief_flyer_url')} placeholder="https://…" disabled={readOnly} />
          </div>
        </div>
      </AffCard>

      <AffCard padding={20}>
        <AffCardHeader icon={Info} title={t('aff.brief.logistics')} subtitle={t('aff.brief.logisticsSub')} />
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <FieldLabel>{t('aff.brief.doorTime')}</FieldLabel>
              <DarkInput value={form.door_time} onChange={set('door_time')} placeholder="22:00" disabled={readOnly} />
            </div>
            <div>
              <FieldLabel>{t('aff.brief.dressCode')}</FieldLabel>
              <DarkInput value={form.dress_code} onChange={set('dress_code')} placeholder={t('aff.brief.dressCodePh')} disabled={readOnly} />
            </div>
          </div>
          <div>
            <FieldLabel>{t('aff.brief.lineup')}</FieldLabel>
            <DarkTextarea value={form.lineup_notes} onChange={set('lineup_notes')} placeholder={t('aff.brief.lineupPh')} rows={2} disabled={readOnly} />
          </div>
          <div>
            <FieldLabel>{t('aff.brief.promoNotes')}</FieldLabel>
            <DarkTextarea value={form.promo_notes} onChange={set('promo_notes')} placeholder={t('aff.brief.promoNotesPh')} rows={3} disabled={readOnly} />
          </div>
          <div>
            <FieldLabel>{t('aff.brief.extraInfo')}</FieldLabel>
            <DarkTextarea value={form.extra_info} onChange={set('extra_info')} placeholder={t('aff.brief.extraInfoPh')} rows={2} disabled={readOnly} />
          </div>
        </div>
      </AffCard>

      {!readOnly && (
        <div className="flex justify-end">
          <AffButton onClick={handleSave} disabled={saving}>
            <Save className="h-4 w-4" /> {saving ? t('aff.brief.saving') : t('aff.brief.saveBtn')}
          </AffButton>
        </div>
      )}
    </AffPage>
  );
}
