import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/use-toast';
import { useUnsavedGuard } from '@/hooks/useUnsavedGuard';
import { ArrowLeft, Save, Sparkles, Megaphone, Info } from 'lucide-react';
import {
  AffPage, AffCard, AffCardHeader, AffButton, Pill, AffSpinner,
  FieldLabel, DarkInput, DarkTextarea,
  T1, T3, INNER_BG, BORDER,
} from '@/components/affiliate/affiliate-ui';

type BriefForm = {
  instagram_caption: string;
  hashtags: string;
  door_time: string;
  dress_code: string;
  lineup_notes: string;
  promo_notes: string;
  extra_info: string;
  brief_flyer_url: string;
};

const EMPTY_FORM: BriefForm = {
  instagram_caption: '', hashtags: '', door_time: '', dress_code: '',
  lineup_notes: '', promo_notes: '', extra_info: '', brief_flyer_url: '',
};

export default function AffiliateEventBrief() {
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const { toast } = useToast();
  const [eventName, setEventName] = useState('');
  const [form, setForm] = useState<BriefForm>(EMPTY_FORM);
  const [briefId, setBriefId] = useState<string | null>(null);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (user && id) fetchBrief();
  }, [user?.id, id]);

  const fetchBrief = async () => {
    setLoading(true);
    const { data: aff } = await supabase.from('affiliates').select('id').eq('user_id', user!.id).single();
    if (!aff) { setLoading(false); return; }

    const { data: ev } = await supabase
      .from('affiliate_events')
      .select('name')
      .eq('id', id!)
      .eq('affiliate_id', aff.id)
      .maybeSingle();
    if (!ev) { setLoading(false); return; }
    setEventName(ev.name);

    const { data: brief } = await supabase
      .from('affiliate_event_briefs')
      .select('*')
      .eq('affiliate_event_id', id!)
      .maybeSingle();

    if (brief) {
      setBriefId(brief.id);
      setIsAutoGenerated(brief.is_auto_generated ?? false);
      setForm({
        instagram_caption: brief.instagram_caption ?? '',
        hashtags: brief.hashtags ?? '',
        door_time: brief.door_time ?? '',
        dress_code: brief.dress_code ?? '',
        lineup_notes: brief.lineup_notes ?? '',
        promo_notes: brief.promo_notes ?? '',
        extra_info: brief.extra_info ?? '',
        brief_flyer_url: brief.brief_flyer_url ?? '',
      });
    }
    setLoading(false);
  };

  const handleSave = async (): Promise<boolean> => {
    setSaving(true);
    const payload = {
      affiliate_event_id: id!,
      instagram_caption: form.instagram_caption || null,
      hashtags: form.hashtags || null,
      door_time: form.door_time || null,
      dress_code: form.dress_code || null,
      lineup_notes: form.lineup_notes || null,
      promo_notes: form.promo_notes || null,
      extra_info: form.extra_info || null,
      brief_flyer_url: form.brief_flyer_url || null,
      is_auto_generated: false,
    };

    let error;
    if (briefId) {
      ({ error } = await supabase.from('affiliate_event_briefs').update(payload).eq('id', briefId));
    } else {
      const { data, error: insertError } = await supabase
        .from('affiliate_event_briefs')
        .insert(payload)
        .select('id')
        .single();
      error = insertError;
      if (data) setBriefId(data.id);
    }

    setSaving(false);
    if (error) {
      toast({ title: 'Erreur', description: error.message, variant: 'destructive' });
      return false;
    }
    setIsAutoGenerated(false);
    markSaved();
    toast({ title: 'Brief sauvegardé' });
    return true;
  };

  const { markSaved, guardedNavigate } = useUnsavedGuard({
    scope: `affiliate-brief:${id ?? 'new'}`,
    label: 'Brief soirée',
    ready: !loading,
    value: form,
    onRestore: setForm,
    onSave: handleSave,
  });

  const set = (key: keyof BriefForm) => (v: string) => setForm(f => ({ ...f, [key]: v }));

  if (loading) return <AffSpinner />;

  return (
    <AffPage maxWidth={760}>
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex items-center gap-3">
        <button onClick={() => guardedNavigate('/affiliate/events')}
          className="flex items-center justify-center transition-colors flex-none"
          style={{ width: 36, height: 36, borderRadius: 10, background: INNER_BG, border: `1px solid ${BORDER}`, color: T3 }}
          onMouseEnter={(e) => (e.currentTarget.style.color = T1)} onMouseLeave={(e) => (e.currentTarget.style.color = T3)}>
          <ArrowLeft className="h-4 w-4" />
        </button>
        <div className="flex-1 min-w-0">
          <h1 style={{ color: T1, fontSize: 'clamp(20px,2.4vw,26px)', fontWeight: 680, letterSpacing: '-0.02em', margin: 0 }}>Brief soirée</h1>
          <p className="truncate" style={{ color: T3, fontSize: 13, marginTop: 2 }}>{eventName}</p>
        </div>
        {isAutoGenerated && <Pill tone="red"><span className="inline-flex items-center gap-1"><Sparkles className="h-3 w-3" /> Auto-généré</span></Pill>}
      </motion.div>

      <AffCard padding={20}>
        <AffCardHeader icon={Megaphone} title="Contenu promotionnel" subtitle="Ce que les promoteurs publient" accent />
        <div className="space-y-4">
          <div>
            <FieldLabel>Caption Instagram</FieldLabel>
            <DarkTextarea value={form.instagram_caption} onChange={set('instagram_caption')} placeholder="Texte de la publication Instagram…" rows={5} />
          </div>
          <div>
            <FieldLabel>Hashtags</FieldLabel>
            <DarkInput value={form.hashtags} onChange={set('hashtags')} placeholder="#nightlife #paris #soiree…" />
          </div>
          <div>
            <FieldLabel hint="(peut différer du flyer principal)">URL flyer brief</FieldLabel>
            <DarkInput value={form.brief_flyer_url} onChange={set('brief_flyer_url')} placeholder="https://…" />
          </div>
        </div>
      </AffCard>

      <AffCard padding={20}>
        <AffCardHeader icon={Info} title="Infos logistiques" subtitle="Détails pratiques de la soirée" />
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <FieldLabel>Heure des portes</FieldLabel>
              <DarkInput value={form.door_time} onChange={set('door_time')} placeholder="22:00" />
            </div>
            <div>
              <FieldLabel>Dress code</FieldLabel>
              <DarkInput value={form.dress_code} onChange={set('dress_code')} placeholder="Smart casual / Tenue de soirée…" />
            </div>
          </div>
          <div>
            <FieldLabel>Lineup / Artistes</FieldLabel>
            <DarkTextarea value={form.lineup_notes} onChange={set('lineup_notes')} placeholder="DJ Guest, resident…" rows={2} />
          </div>
          <div>
            <FieldLabel>Notes promo</FieldLabel>
            <DarkTextarea value={form.promo_notes} onChange={set('promo_notes')} placeholder="Message clé à transmettre aux clients…" rows={3} />
          </div>
          <div>
            <FieldLabel>Infos supplémentaires</FieldLabel>
            <DarkTextarea value={form.extra_info} onChange={set('extra_info')} placeholder="Parking, accès, VIP…" rows={2} />
          </div>
        </div>
      </AffCard>

      <div className="flex justify-end">
        <AffButton onClick={handleSave} disabled={saving}>
          <Save className="h-4 w-4" /> {saving ? 'Sauvegarde…' : 'Sauvegarder le brief'}
        </AffButton>
      </div>
    </AffPage>
  );
}
