import { Outlet, Navigate } from 'react-router-dom';
import { OwnerPreviewContext } from '@/contexts/OwnerPreviewContext';
import { OwnerPreviewBanner } from '@/components/OwnerPreviewBanner';
import { useAuth } from '@/hooks/useAuth';

/**
 * Layout wrapper for /owner/preview/:slug/* routes.
 *
 * Intentionally lightweight — no Supabase venues query.
 * The link to this route is only generated by OwnerHeader which
 * already knows the authenticated owner's venueId, so we only
 * need to verify the user has the 'owner' role (from their JWT/session).
 *
 * This avoids the blocking venues fetch that can hang indefinitely
 * and cause the infinite spinner seen on slower connections.
 */
export function OwnerPreviewLayout() {
  const { user, loading, roles } = useAuth();

  // Wait for auth session — useAuth resolves in <200ms from session cache
  if (loading) return null;

  // Redirect unauthenticated users
  if (!user) return <Navigate to="/auth" replace />;

  // Only owners can see the preview banner
  if (!roles.includes('owner' as any)) return <Navigate to="/" replace />;

  return (
    <OwnerPreviewContext.Provider value={{ isPreview: true }}>
      <OwnerPreviewBanner />
      {/* Push page content below the fixed 44px banner */}
      <div style={{ paddingTop: 44 }}>
        <Outlet />
      </div>
    </OwnerPreviewContext.Provider>
  );
}
