import type { CrmDict } from './types';

// Compte › Aide et contact : les réponses fréquentes — [EN, FR, ES].
const dict: CrmDict = {
  'yc.faq.shotgun.q': ['How do I connect Shotgun?', 'Comment connecter Shotgun ?', '¿Cómo conecto Shotgun?'],
  'yc.faq.shotgun.a': ['In Connectors, paste your Shotgun organizer ID and token. Yuno checks the access, then imports your nights, tickets and buyers in the background. Yuno only reads: nothing changes on Shotgun.', 'Dans Connecteurs, collez votre ID organisateur et votre jeton Shotgun. Yuno vérifie les accès, puis importe vos soirées, vos billets et vos acheteurs en arrière-plan. Yuno ne fait que lire : rien n’est modifié chez Shotgun.', 'En Conectores, pegue su ID de organizador y su token de Shotgun. Yuno comprueba los accesos y luego importa sus fiestas, entradas y compradores en segundo plano. Yuno solo lee: nada cambia en Shotgun.'],
  'yc.faq.shotgun.l': ['Open connectors', 'Ouvrir les connecteurs', 'Abrir conectores'],
  'yc.faq.sync.q': ['How often are my figures updated?', 'À quelle fréquence mes chiffres sont-ils mis à jour ?', '¿Con qué frecuencia se actualizan mis cifras?'],
  'yc.faq.sync.a': ['Yuno reads Shotgun every 15 minutes. The time of the last read shows at the top of each page, and you can start a read at any time from Connectors.', 'Yuno relit Shotgun toutes les 15 minutes. L’heure de la dernière lecture s’affiche en haut de chaque page, et vous pouvez lancer une lecture à tout moment depuis Connecteurs.', 'Yuno vuelve a leer Shotgun cada 15 minutos. La hora de la última lectura aparece arriba de cada página, y puede lanzar una lectura cuando quiera desde Conectores.'],
  'yc.faq.import.q': ['How do I import my customers from a file?', 'Comment importer mes clients depuis un fichier ?', '¿Cómo importo mis clientes desde un archivo?'],
  'yc.faq.import.a': ['In Customers, then Imports, drop a CSV or Excel file. Yuno spots the columns (name, email, phone) and shows a preview before importing. Only contacts who agreed to hear from you receive your campaigns.', 'Dans Clients, puis Imports, déposez un fichier CSV ou Excel. Yuno repère les colonnes (nom, e-mail, téléphone) et vous montre un aperçu avant d’importer. Seuls les contacts qui ont accepté de vous lire reçoivent vos campagnes.', 'En Clientes y luego Importaciones, suelte un archivo CSV o Excel. Yuno detecta las columnas (nombre, e-mail, teléfono) y muestra una vista previa antes de importar. Solo los contactos que aceptaron recibir sus mensajes reciben sus campañas.'],
  'yc.faq.import.l': ['Open imports', 'Ouvrir les imports', 'Abrir importaciones'],
  'yc.faq.cost.q': ['How much does a send cost?', 'Combien coûte un envoi ?', '¿Cuánto cuesta un envío?'],
  'yc.faq.cost.a': ['An email costs 1 Yunit. Before each send, Yuno shows its cost and your balance. If some are missing, you top up without leaving the screen. A test email costs nothing.', 'Un e-mail coûte 1 Yunit. Avant chaque envoi, Yuno affiche son coût et votre solde. S’il en manque, vous rechargez sans quitter l’écran. Un e-mail de test ne coûte rien.', 'Un e-mail cuesta 1 Yunit. Antes de cada envío, Yuno muestra su coste y su saldo. Si faltan, recarga sin salir de la pantalla. Un e-mail de prueba no cuesta nada.'],
  'yc.faq.cost.l': ['Top up Yunits', 'Recharger des Yunits', 'Recargar Yunits'],
  'yc.faq.order.q': ['Which Yunits are used first?', 'Quels Yunits sont utilisés en premier ?', '¿Qué Yunits se usan primero?'],
  'yc.faq.order.a': ['Those that expire first: the free Yunits of the month, then those you bought, valid one year.', 'Ceux qui expirent le plus tôt : les Yunits offerts du mois, puis ceux que vous avez achetés, valables un an.', 'Los que caducan antes: los Yunits gratuitos del mes, luego los que compró, válidos un año.'],
  'yc.faq.order.l': ['See my balance', 'Voir mon solde', 'Ver mi saldo'],
  'yc.faq.skip.q': ['Why didn’t a contact receive anything?', 'Pourquoi un contact n’a-t-il rien reçu ?', '¿Por qué un contacto no recibió nada?'],
  'yc.faq.skip.a': ['Yuno only sends to contacts who agreed to your emails, and sets aside those better not to overload. Those contacts don’t use Yunits.', 'Yuno n’envoie qu’aux contacts qui ont accepté vos e-mails, et écarte ceux qu’il vaut mieux ne pas saturer. Ces contacts ne consomment pas de Yunits.', 'Yuno solo envía a los contactos que aceptaron sus e-mails, y aparta a los que conviene no saturar. Esos contactos no consumen Yunits.'],
  'yc.faq.regular.q': ['What is a regular?', 'Qu’est-ce qu’un habitué ?', '¿Qué es un habitual?'],
  'yc.faq.regular.a': ['By default, a customer who came to 3 nights or more over the last 6 months. A dormant customer hasn’t come back for 4 months. You set these thresholds in Settings.', 'Par défaut, un client venu à 3 soirées ou plus sur les 6 derniers mois. Un endormi n’est pas revenu depuis 4 mois. Ces seuils se règlent dans Réglages.', 'Por defecto, un cliente que vino a 3 fiestas o más en los últimos 6 meses. Un dormido no ha vuelto en 4 meses. Estos umbrales se ajustan en Ajustes.'],
  'yc.faq.regular.l': ['See my customers', 'Voir mes clients', 'Ver mis clientes'],
  'yc.faq.team.q': ['How do I add someone to my team?', 'Comment ajouter quelqu’un à mon équipe ?', '¿Cómo añado a alguien a mi equipo?'],
  'yc.faq.team.a': ['In Team and access, click Invite, enter their email and pick a role: Administrator, Editor or Viewer. The person gets a link valid 7 days.', 'Dans Équipe et accès, cliquez sur Inviter, saisissez son e-mail et choisissez un rôle : Administrateur, Éditeur ou Lecteur. La personne reçoit un lien valable 7 jours.', 'En Equipo y accesos, haga clic en Invitar, escriba su e-mail y elija un rol: Administrador, Editor o Lector. La persona recibe un enlace válido 7 días.'],
  'yc.faq.team.l': ['Open the team', 'Ouvrir l’équipe', 'Abrir el equipo'],
  'yc.faq.invoices.q': ['Where do I download my invoices?', 'Où télécharger mes factures ?', '¿Dónde descargo mis facturas?'],
  'yc.faq.invoices.a': ['In Subscription and billing, Invoices section: each invoice downloads as a PDF.', 'Dans Abonnement et facturation, section Factures : chaque facture se télécharge en PDF.', 'En Suscripción y facturación, sección Facturas: cada factura se descarga en PDF.'],
  'yc.faq.invoices.l': ['Open billing', 'Ouvrir la facturation', 'Abrir la facturación'],
  'yc.faq.cancel.q': ['What happens if I cancel?', 'Que se passe-t-il si je résilie ?', '¿Qué pasa si cancelo?'],
  'yc.faq.cancel.l': ['Open billing', 'Ouvrir la facturation', 'Abrir la facturación'],
  'yc.faq.cancel.a': ['The subscription stays active until the end of the paid period. Then your account is paused: your base stays readable and exportable, nothing syncs or leaves. Your bought Yunits stay valid one year, the free ones expire. You can subscribe again at any time.', 'L’abonnement reste actif jusqu’à la fin de la période payée. Ensuite, votre compte est en pause : votre base reste lisible et exportable, rien ne se synchronise ni ne part. Vos Yunits achetés restent valables un an, les offerts expirent. Vous pouvez vous réabonner à tout moment.', 'La suscripción sigue activa hasta el final del periodo pagado. Después su cuenta queda en pausa: su base sigue legible y exportable, nada se sincroniza ni sale. Sus Yunits comprados siguen válidos un año, los gratuitos caducan. Puede volver a suscribirse cuando quiera.'],
  'yc.faq.ticketing.q': ['Can I also sell my tickets with Yuno?', 'Puis-je aussi vendre mes billets avec Yuno ?', '¿Puedo vender también mis entradas con Yuno?'],
  'yc.faq.ticketing.l': ['Open Yuno Ticketing', 'Ouvrir Yuno Billetterie', 'Abrir Yuno Ticketing'],
  'yc.faq.ticketing.a': ['Yes. Yuno Ticketing (tickets, VIP tables, guest lists) opens on this same account, with no subscription: same login, same contacts. Only the account holder can open it. Once open, "Yuno Ticketing" at the foot of the menu takes you to its console, and "Open Yuno CRM" there brings you back. Your CRM, its Yunits and its subscription don’t change.', 'Oui. Yuno Billetterie (billets, tables VIP, guest lists) s’ouvre sur ce même compte, sans abonnement : même connexion, mêmes contacts. Seul le titulaire du compte peut l’ouvrir. Une fois ouverte, « Yuno Billetterie » au pied du menu mène à sa console, et « Ouvrir Yuno CRM » vous ramène ici. Votre CRM, ses Yunits et son abonnement ne changent pas.', 'Sí. Yuno Ticketing (entradas, mesas VIP, guest lists) se abre en esta misma cuenta, sin suscripción: mismo acceso, mismos contactos. Solo el titular de la cuenta puede abrirlo. Una vez abierto, «Yuno Ticketing» al pie del menú lleva a su consola y «Abrir Yuno CRM» le trae de vuelta. Su CRM, sus Yunits y su suscripción no cambian.'],
};

export default dict;
