-- Purge advance recurring events published with the wrong week's ticket link.
-- These were generated by the bug where upcomingDatesForDayOfWeek returned 2 dates
-- when today was the event day and advance_days >= 7, causing the second (future)
-- occurrence to inherit the current template publication_url.
-- Fix: reset them to draft with no ticket URL so each week gets its own link.

WITH ranked_future AS (
  SELECT
    ae.id,
    ROW_NUMBER() OVER (
      PARTITION BY ae.recurring_template_id
      ORDER BY ae.event_date ASC
    ) AS rn
  FROM affiliate_events ae
  WHERE ae.recurring_template_id IS NOT NULL
    AND ae.event_date >= CURRENT_DATE
)
UPDATE affiliate_events
SET
  status = 'draft',
  external_ticket_url = NULL
WHERE id IN (
  SELECT id FROM ranked_future WHERE rn > 1
)
AND external_ticket_url IS NOT NULL;
